// ─── Portfolio Content Data ───────────────────────────────────────────────────

export const CONTENT = {
  en: {
    navLinks: [
      { label: "Featured", href: "#featured" },
      { label: "Projects", href: "#projects" },
      { label: "Skills",   href: "#skills"   },
      { label: "Hackathons", href: "#hackathons" },
      { label: "About",        href: "#about"        },
      { label: "Publications", href: "#publications" },
      { label: "Contact",      href: "#contact"      },
    ],
    bootLines: [
      "> Booting recruiter-ready portfolio interface...",
      "[ OK ] Computer vision modules indexed",
      "[ OK ] Edge systems telemetry linked",
      "[ OK ] Professional signal calibrated",
    ],
    hero: {
      role: "AI & Computer Vision Developer",
      name: "Luiz Wessel",
      tagline: "Engineering AI systems from the edge of the void.",
      description: "I build practical AI, computer vision, and edge systems with clear interfaces, measurable behavior, and documentation that helps teams understand the system.",
      ctaPrimary: "Review Featured Work",
      ctaSecondary: "Get in Touch",
      hudSignal: "SIGNAL: HUMAN-READABLE AI",
      hudStatus: "STATUS: AVAILABLE",
    },
    featured: {
      label: "// Featured Project",
      title: "A project framed as an engineering case study",
      intro: "A portfolio highlight focused on the work recruiters care about: what problem was solved, how the system was designed, and which technical decisions made it useful.",
      problemLabel: "Problem",
      solutionLabel: "Solution",
      signalLabel: "Technical Signal",
      techLabel: "Technologies",
      metricsLabel: "Measured Results",
      githubBtn: "GitHub Repository",
      demoBtn: "Live Demo",
      project: {
        title: "Gate Vision — Vehicular Access Control",
        category: "Featured Case Study",
        problem: "Condominiums need reliable, automated vehicle access without a manual operator — and the solution must work in real-world lighting with Mercosul plates.",
        solution: "Python/FastAPI backend runs YOLO detection + EasyOCR with CLAHE preprocessing; React admin dashboard via Supabase handles residents, logs, and camera config; Arduino receives serial commands to physically open the gate.",
        technologies: ["Python","YOLO","EasyOCR","FastAPI","React","Supabase","Arduino","OpenCV"],
        github: "https://github.com/Wessel2007/Gate-Vision",
        demo: null,
        signal: "End-to-end system thinking: CV pipeline + REST API + hardware actuation + admin interface",
        status: "done",
        metrics: [
          { value: "98%", label: "Plate detection accuracy (YOLO)" },
          { value: "93%", label: "OCR read accuracy" },
          { value: "4.5s", label: "Avg. processing time per vehicle" },
          { value: "750+", label: "Plate images tested" },
        ],
      },
    },
    projects: {
      label: "// Project Archive",
      title: "Selected Work",
      problemLabel: "Problem",
      solutionLabel: "Solution",
      githubLabel: "GitHub",
      demoLabel: "Demo",
      items: [
        { title:"SteamLine — ETL vs ELT Data Warehouse", category:"Data Engineering", problem:"Which data pipeline architecture performs better on real-world analytical workloads — ETL or ELT?", solution:"Two parallel pipelines (Star Schema DW via DuckDB + Data Lake Medallion via Delta Lake) process the same 13k Steam dataset, answering the same 5 business questions for cross-validation.", technologies:["Python","DuckDB","Delta Lake","Apache Parquet","Pandas"], github:"https://github.com/Wessel2007/SteamLine", demo:null, status:"done" },
        { title:"PaletteAI — AI Color Palette Generator", category:"Generative AI", problem:"Designers need quick, creative color palettes either from image references or conceptual vibes.", solution:"Streamlit app with two modes: dominant color extraction from uploaded images (ColorThief) and LLM-based palette generation from mood descriptions via Groq's Llama 3.1.", technologies:["Python","Streamlit","Groq","Llama 3.1","ColorThief","Pillow"], github:"https://github.com/Wessel2007/PaletteAI", demo:null, status:"done" },
        { title:"Vehicle Plate Detection", category:"Computer Vision", problem:"Detecting Mercosul plates in real-world images requires a robust, reusable module before any OCR or access-control logic.", solution:"Trained YOLOv11 to locate plate regions, applied CLAHE contrast enhancement and a fast crop pipeline feeding clean images to downstream OCR.", technologies:["Python","YOLOv11","OpenCV","PyTorch","NumPy"], github:"https://github.com/Wessel2007/deteccao-placas-veiculares", demo:null, status:"done" },
        { title:"Corn Instance Segmentation", category:"Computer Vision", problem:"Measuring and segmenting individual corn plants requires precise instance-level detection for agricultural analysis.", solution:"Built a CV pipeline using CVAT for annotation, OpenCV for processing, and Python for instance segmentation of real field images.", technologies:["Python","OpenCV","CVAT"], github:"https://github.com/Wessel2007/corn-instance-segmentation", demo:null, status:"done" },
        { title:"Crypto Insight AI", category:"Applied AI / Finance", problem:"Tracking technical indicators across timeframes for multiple cryptos is hard to interpret without a unified scoring layer.", solution:"FastAPI backend pulls live data via CCXT, computes RSI/EMA/MACD, runs a weighted scoring engine, calls Claude for plain-language summaries.", technologies:["Python","FastAPI","CCXT","Pandas","Claude API","Next.js","TypeScript"], github:"https://github.com/Wessel2007/crypto-insight-ai", demo:null, status:"done" },
        { title:"Raiz Iguaçu — Hackatour 2026", category:"Full-Stack Web", problem:"Community tourism in the Iguaçu region lacks a scalable platform for local producers and travelers.", solution:"Full-stack platform with experience discovery, producer onboarding, admin dashboard with real-time metrics, QR-code totem management, and AI-generated visitor insights.", technologies:["React","TypeScript","Vite","Tailwind","FastAPI","PostgreSQL","shadcn/ui"], github:"https://github.com/Wessel2007/Hackatour-Cataratas", demo:null, status:"done" },
        { title:"Pharm Assist", category:"Applied AI", problem:"Public pharmacy management needed an AI-assisted tool to track and optimize medication dispensing processes.", solution:"Collaborative academic project with Biopark AI course for the Prefeitura de Toledo/PR, applying AI to pharmacy workflows.", technologies:["Python","AI/ML"], github:"https://github.com/Wessel2007/Pharm-Assist", demo:null, status:"done" },
        { title:"New AI Invest", category:"Web / Finance", problem:"Investors managing multiple asset classes need a clear view of portfolio drift without relying on spreadsheets.", solution:"React SPA with full asset CRUD, configurable target allocations, rebalancing calculator, Recharts dashboards, and diversification insights.", technologies:["React","JavaScript","Tailwind CSS","Recharts"], github:"https://github.com/Wessel2007/new-ai-invest", demo:null, status:"done" },
        { title:"Neural HUD Portfolio", category:"Web Interface", problem:"Technical portfolios often fail to communicate engineering judgment or how problems were actually solved.", solution:"Portfolio built with React 18 + Vite — Canvas API particle background, custom HUD animations, bilingual support, and a design system in vanilla CSS.", technologies:["React","JavaScript","Canvas API","CSS","Vite"], github:"https://github.com/Wessel2007/Neural-HUD-Portfolio-AI-Developer-Interface", demo:null, status:"dev" },
        { title:"Tornado Brasil — Storm Prediction", category:"AI / Meteorology", problem:"Southern Brazil has documented tornado activity but lacks accessible, automated risk-mapping tools to alert communities before extreme weather events.", solution:"Planned ML system to process meteorological data (INMET/ERA5), identify historical storm patterns, and generate regional risk maps for the South of Brazil. Currently in early development.", technologies:["Python","Machine Learning","Pandas","NumPy","Data Science"], github:"https://github.com/Wessel2007/tornado_project", demo:null, status:"dev" },
        { title:"Biopark Hackathon — Protocol Tracker", category:"Full-Stack / Applied AI", problem:"Tracking construction and business protocols across multiple public agencies (cartórios, COPEL, SANEPAR, CBPR) requires constant manual monitoring with no centralized view.", solution:"Web platform with automated Playwright scraping of real public portals, AI chat assistant via Ollama/Llama, PDF reports, screenshot evidence logging, and a full admin dashboard. Built during hackathon.", technologies:["Python","FastAPI","React","Vite","Tailwind","Supabase","Playwright","Ollama"], github:"https://github.com/Wessel2007/hackathon-biopark", demo:null, status:"done" },
        { title:"Fornalha — Addiction Recovery App", category:"Mobile Development", problem:"Existing sobriety trackers are generic day counters that don't sustain long-term motivation for pornography-addiction recovery specifically.", solution:"React Native/Expo app with a narrative rank progression (Recruta → Imortal), a 9-screen personalized onboarding, a panic-button flow with guided breathing, a trigger journal with pattern insights, and AES-256-GCM local encryption for sensitive data — fully internationalized (pt-BR/en/es). Ships with a dedicated marketing site including privacy policy and terms of service.", technologies:["React Native","Expo","TypeScript","i18next","Reanimated"], github:"https://github.com/Wessel2007/projeto_vicio", demo:null, status:"dev" },
        { title:"Negociador de Dívidas", category:"Full-Stack Web / FinTech", problem:"People struggling with debt lack a tool to prioritize what to pay first, flag abusive collection practices, and draft formal contestations.", solution:"Next.js 14 MVP with avalanche/snowball payoff-strategy calculators, rule-based alerts for undue charges, and auto-generated contestation drafts for Procon/BACEN — Prisma schema already modeled for the upcoming Postgres integration.", technologies:["Next.js","TypeScript","Tailwind CSS","Prisma","Zod","Vitest"], github:"https://github.com/Wessel2007/negociador_dividas", demo:null, status:"dev" },
        { title:"Telegram AI Assistant Bot", category:"Automation / AI Integration", problem:"Needed a hands-on way to learn visual workflow automation and wire an LLM into a real messaging channel without writing a custom backend.", solution:"n8n workflow (self-hosted via Docker) that receives Telegram messages through a webhook, forwards them to the Google Gemini API, and replies in real time — fully orchestrated with no custom server code.", technologies:["n8n","Docker","Gemini API"], github:"https://github.com/Wessel2007/telegram-gemini-bot", demo:null, status:"done" },
      ],
    },
    skills: {
      label: "// Tech Stack",
      title: "Domain Architecture",
      description: "Stack organized by system responsibility — not arbitrary language lists. Each layer reflects a distinct role in how I build intelligent, end-to-end software: from local AI inference to automated web scraping.",
      layers: [
        { index:"01", title:"Interface Layer",    technologies:["React","Next.js","React Native","Expo","TypeScript","JavaScript","HTML","CSS","Tailwind","shadcn/ui","Framer Motion"] },
        { index:"02", title:"Intelligence Layer", technologies:["Python","YOLO","OpenCV","PyTorch","NumPy","Pandas","OCR","Ollama","Roboflow","CVAT"] },
        { index:"03", title:"Data Layer",         technologies:["PostgreSQL","MySQL","Supabase","Prisma","SQL","DBeaver"] },
        { index:"04", title:"Integration Layer",  technologies:["FastAPI","Playwright","REST APIs","n8n","Arduino","IoT","Airflow"] },
        { index:"05", title:"Deployment Layer",   technologies:["Git","GitHub","Docker","Vercel"] },
      ],
    },
    hackathons: {
      label: "// Hackathons & Recognition",
      title: "Under Pressure, On the Podium",
      description: "Short timelines, real judging panels, and working software by the deadline — a different kind of technical proof than a portfolio project.",
      items: [
        {
          place: "3rd Place",
          award: "Awarded",
          title: "Biopark Hackathon — Protocol Tracker",
          org: "Biopark",
          description: "Built an automated protocol-tracking platform (Playwright scraping + Ollama AI assistant + admin dashboard) from scratch during the event. Placed 3rd overall and received a prize.",
          highlight: true,
        },
        {
          place: "4th Place",
          award: "Finalist",
          title: "Hackatour 2026 — Raiz Iguaçu",
          org: "Hackatour",
          description: "Designed and shipped a full-stack tourism platform for local producers in the Iguaçu region, including a real-time admin dashboard and QR-code totem management. Finished 4th, without prize.",
          highlight: false,
        },
      ],
    },
    about: {
      label: "// About",
      title: "Engineer in Training, Builder by Practice",
      bio: [
        "I'm an AI and Computer Vision student/developer focused on turning difficult technical ideas into working prototypes that are easy to inspect, explain, and improve.",
        "My strongest projects sit between model behavior and real-world constraints: image pipelines, sensor-driven systems, edge prototypes, and the dashboards that make results readable.",
        "I care about clean implementation, honest evaluation, and interfaces that make engineering decisions visible without turning the product into visual noise.",
      ],
      signalLabel: "Current Signal",
      signal: "Looking for internships, junior roles, research collaborations, and project work around AI, Computer Vision, and edge systems.",
      stats: [
        { value:"14",  label:"Projects Built" },
        { value:"2",   label:"Hackathons" },
        { value:"25+", label:"Technologies" },
        { value:"5",   label:"Tech Domains" },
      ],
    },
    publications: {
      label: "// Research",
      title: "Scientific Publications",
      description: "Peer-reviewed research at the intersection of machine learning and clinical decision support.",
      countLabel: "Published Article",
      readBtn: "Read Article",
      items: [
        {
          title: "Machine Learning in Heart Disease Prediction: A Comparative Analysis of Classification Algorithms",
          journal: "Revista Eletrônica Multidisciplinar de Investigação Científica (REMICI)",
          volume: "Vol. 5, No. 23 · 2026",
          doi: "https://doi.org/10.47402/remici.v5n23696926",
          url: "https://remici.com.br/index.php/revista/article/view/970",
          keywords: ["Machine Learning", "Heart Disease", "Random Forest", "Classification", "Clinical Decision Support"],
          abstract: "Develops and evaluates five supervised ML models using the Cleveland Heart Disease dataset (303 records, 13 clinical attributes). Cross-validation accuracy between 77.18%–83.45%; Random Forest achieved the highest AUC (90.10%) and recall for positive cases (96.97%), suggesting strong potential as a clinical decision-support tool.",
          license: "CC BY-NC-SA 4.0",
        },
      ],
    },
    contact: {
      label: "// Contact",
      title: "Ready to connect the signal.",
      description: "If you are hiring for AI, Computer Vision, full-stack prototyping, or hardware-adjacent software, this is the fastest route to reach me.",
      links: [
        { label:"GitHub",   href:"https://github.com/Wessel2007",              tag:"CODE"    },
        { label:"LinkedIn", href:"https://www.linkedin.com/in/luizwessel/",    tag:"NETWORK" },
        { label:"Email",    href:"mailto:heyxist3r@gmail.com",                 tag:"DIRECT"  },
      ],
      footerBuild:  "BUILD: REACT 18 / VITE / CANVAS API",
      footerStatus: "SYSTEM STATUS: OPEN TO OPPORTUNITIES",
      footerSync:   "LAST SYNC: 2026 / PORT_OS v3.0",
    },
  },

  pt: {
    navLinks: [
      { label: "Destaque",  href: "#featured" },
      { label: "Projetos",  href: "#projects"  },
      { label: "Skills",    href: "#skills"    },
      { label: "Hackathons", href: "#hackathons" },
      { label: "Sobre",        href: "#about"        },
      { label: "Publicações",  href: "#publications" },
      { label: "Contato",      href: "#contact"      },
    ],
    bootLines: [
      "> Iniciando interface de portfólio...",
      "[ OK ] Módulos de visão computacional indexados",
      "[ OK ] Telemetria de sistemas embarcados vinculada",
      "[ OK ] Sinal profissional calibrado",
    ],
    hero: {
      role: "Desenvolvedor de IA & Visão Computacional",
      name: "Luiz Wessel",
      tagline: "Construindo sistemas de IA na fronteira do desconhecido.",
      description: "Desenvolvo sistemas práticos de IA, visão computacional e edge computing com interfaces claras, comportamento mensurável e documentação que ajuda equipes a entender o sistema.",
      ctaPrimary: "Ver Projeto em Destaque",
      ctaSecondary: "Entrar em Contato",
      hudSignal: "SINAL: IA LEGÍVEL POR HUMANOS",
      hudStatus: "STATUS: DISPONÍVEL",
    },
    featured: {
      label: "// Projeto em Destaque",
      title: "Um projeto como estudo de caso de engenharia",
      intro: "Destaque focado no que recrutadores realmente querem ver: qual problema foi resolvido, como o sistema foi projetado e quais decisões técnicas o tornaram útil.",
      problemLabel: "Problema",
      solutionLabel: "Solução",
      signalLabel: "Sinal Técnico",
      techLabel: "Tecnologias",
      metricsLabel: "Resultados Medidos",
      githubBtn: "Repositório GitHub",
      demoBtn: "Demo ao Vivo",
      project: {
        title: "Gate Vision — Controle de Acesso Veicular",
        category: "Estudo de Caso em Destaque",
        problem: "Condomínios precisam de controle de acesso veicular automatizado — e a solução precisa funcionar em condições reais de iluminação com placas Mercosul.",
        solution: "Backend Python/FastAPI com pipeline YOLO + EasyOCR e pré-processamento CLAHE; dashboard React via Supabase para moradores, logs e câmeras; Arduino recebe comandos seriais para abertura física da cancela.",
        technologies: ["Python","YOLO","EasyOCR","FastAPI","React","Supabase","Arduino","OpenCV"],
        github: "https://github.com/Wessel2007/Gate-Vision",
        demo: null,
        signal: "Pensamento ponta a ponta: pipeline CV + API REST + atuação em hardware + interface administrativa",
        status: "done",
        metrics: [
          { value: "98%", label: "Acurácia de detecção da placa (YOLO)" },
          { value: "93%", label: "Acurácia de leitura do OCR" },
          { value: "4,5s", label: "Tempo médio de processamento por veículo" },
          { value: "750+", label: "Imagens de placas testadas" },
        ],
      },
    },
    projects: {
      label: "// Arquivo de Projetos",
      title: "Trabalhos Selecionados",
      problemLabel: "Problema",
      solutionLabel: "Solução",
      githubLabel: "GitHub",
      demoLabel: "Demo",
        items: [
        { title:"SteamLine — ETL vs ELT Data Warehouse", category:"Engenharia de Dados", problem:"Qual arquitetura de pipeline é mais eficiente em cargas analíticas reais — ETL ou ELT?", solution:"Dois pipelines paralelos (DW Star Schema via DuckDB + Data Lake Medallion via Delta Lake) processam o mesmo dataset de 13k jogos da Steam, respondendo às mesmas 5 perguntas de negócio para validação cruzada.", technologies:["Python","DuckDB","Delta Lake","Apache Parquet","Pandas"], github:"https://github.com/Wessel2007/SteamLine", demo:null, status:"done" },
        { title:"PaletteAI — Gerador de Paletas com IA", category:"IA Generativa", problem:"Designers precisam de paletas de cores rápidas e criativas a partir de imagens de referência ou vibes conceituais.", solution:"App Streamlit com dois modos: extração de cores dominantes de imagens (ColorThief) e geração de paletas por LLM a partir de descrições de clima via API Groq com Llama 3.1.", technologies:["Python","Streamlit","Groq","Llama 3.1","ColorThief","Pillow"], github:"https://github.com/Wessel2007/PaletteAI", demo:null, status:"done" },
        { title:"Detecção de Placas Veiculares", category:"Visão Computacional", problem:"Detectar placas Mercosul em imagens reais exige módulo robusto antes de qualquer lógica de OCR.", solution:"Treinei YOLOv11 para localizar placas, apliquei CLAHE e implementei pipeline de recorte para OCR.", technologies:["Python","YOLOv11","OpenCV","PyTorch","NumPy"], github:"https://github.com/Wessel2007/deteccao-placas-veiculares", demo:null, status:"done" },
        { title:"Segmentação de Milho", category:"Visão Computacional", problem:"Medir e segmentar plantas de milho exige detecção precisa no nível de instância.", solution:"Pipeline de CV com CVAT para anotação, OpenCV para processamento e Python para segmentação.", technologies:["Python","OpenCV","CVAT"], github:"https://github.com/Wessel2007/corn-instance-segmentation", demo:null, status:"done" },
        { title:"Crypto Insight AI", category:"IA Aplicada / Finanças", problem:"Acompanhar indicadores técnicos em múltiplos timeframes é difícil sem uma camada unificada de scoring.", solution:"Backend FastAPI com CCXT, computa RSI/EMA/MACD, engine de scoring ponderado e Claude para resumos em linguagem natural.", technologies:["Python","FastAPI","CCXT","Pandas","Claude API","Next.js","TypeScript"], github:"https://github.com/Wessel2007/crypto-insight-ai", demo:null, status:"done" },
        { title:"Raiz Iguaçu — Hackatour 2026", category:"Full-Stack Web", problem:"Turismo comunitário no Iguaçu sem plataforma escalável para produtores e turistas.", solution:"Plataforma full-stack com descoberta de experiências, dashboard admin, totens QR Code e insights de IA.", technologies:["React","TypeScript","Vite","Tailwind","FastAPI","PostgreSQL","shadcn/ui"], github:"https://github.com/Wessel2007/Hackatour-Cataratas", demo:null, status:"done" },
        { title:"Pharm Assist", category:"IA Aplicada", problem:"Gestão farmacêutica municipal precisava de ferramenta com IA para monitorar dispensação.", solution:"Projeto acadêmico com Biopark AI para Prefeitura de Toledo/PR, aplicando IA em workflows farmacêuticos.", technologies:["Python","IA/ML"], github:"https://github.com/Wessel2007/Pharm-Assist", demo:null, status:"done" },
        { title:"New AI Invest", category:"Web / Finanças", problem:"Investidores precisam de visão clara do desvio do portfólio sem depender de planilhas.", solution:"SPA React com CRUD de ativos, alocações-alvo, calculadora de rebalanceamento e dashboards Recharts.", technologies:["React","JavaScript","Tailwind CSS","Recharts"], github:"https://github.com/Wessel2007/new-ai-invest", demo:null, status:"done" },
        { title:"Neural HUD Portfolio", category:"Interface Web", problem:"Portfólios técnicos falham em comunicar julgamento de engenharia e contexto dos projetos.", solution:"Portfólio construído com React 18 + Vite — partículas Canvas API, animações HUD customizadas, suporte bilíngue e design system em CSS puro.", technologies:["React","JavaScript","Canvas API","CSS","Vite"], github:"https://github.com/Wessel2007/Neural-HUD-Portfolio-AI-Developer-Interface", demo:null, status:"dev" },
        { title:"Tornado Brasil — Previsão de Tempestades", category:"IA / Meteorologia", problem:"O sul do Brasil tem registro de tornados mas carece de ferramentas automatizadas de mapeamento de risco para alertar comunidades antes de eventos extremos.", solution:"Sistema de ML planejado para processar dados meteorológicos (INMET/ERA5), identificar padrões históricos de tempestades e gerar mapas de risco regional para o sul do Brasil. Em desenvolvimento inicial.", technologies:["Python","Machine Learning","Pandas","NumPy","Data Science"], github:"https://github.com/Wessel2007/tornado_project", demo:null, status:"dev" },
        { title:"Hackathon Biopark — Rastreador de Protocolos", category:"Full-Stack / IA Aplicada", problem:"Acompanhar protocolos de obras e negócios em múltiplos órgãos públicos (cartórios, COPEL, SANEPAR, CBPR) exige monitoramento manual constante sem visão centralizada.", solution:"Plataforma web com scraping automatizado via Playwright em portais públicos reais, assistente de IA com Ollama/Llama, relatórios PDF, evidências por screenshot e dashboard administrativo. Desenvolvido em hackathon.", technologies:["Python","FastAPI","React","Vite","Tailwind","Supabase","Playwright","Ollama"], github:"https://github.com/Wessel2007/hackathon-biopark", demo:null, status:"done" },
        { title:"Fornalha — App de Recuperação de Vício", category:"Desenvolvimento Mobile", problem:"Apps de sobriedade existentes são contadores de dias genéricos que não sustentam motivação de longo prazo para recuperação de vício em pornografia especificamente.", solution:"App React Native/Expo com progressão narrativa por patentes (Recruta → Imortal), onboarding personalizado de 9 telas, botão de pânico com respiração guiada, diário de gatilhos com insights de padrão e criptografia local AES-256-GCM para dados sensíveis — totalmente internacionalizado (pt-BR/en/es). Acompanha site institucional dedicado com política de privacidade e termos de uso.", technologies:["React Native","Expo","TypeScript","i18next","Reanimated"], github:"https://github.com/Wessel2007/projeto_vicio", demo:null, status:"dev" },
        { title:"Negociador de Dívidas", category:"Full-Stack Web / FinTech", problem:"Pessoas endividadas não têm uma ferramenta para priorizar o que pagar primeiro, identificar cobranças indevidas e redigir contestações formais.", solution:"MVP em Next.js 14 com calculadoras de estratégia de quitação (avalanche/bola de neve), alertas baseados em regras para cobranças indevidas e geração automática de rascunhos de contestação para Procon/BACEN — schema Prisma já modelado para a próxima fase de integração com Postgres.", technologies:["Next.js","TypeScript","Tailwind CSS","Prisma","Zod","Vitest"], github:"https://github.com/Wessel2007/negociador_dividas", demo:null, status:"dev" },
        { title:"Bot Assistente de IA no Telegram", category:"Automação / Integração de IA", problem:"Precisava de uma forma prática de aprender automação visual de workflows e integrar um LLM a um canal de mensagens real sem escrever um backend customizado.", solution:"Workflow n8n (self-hosted via Docker) que recebe mensagens do Telegram via webhook, encaminha para a API do Google Gemini e responde em tempo real — tudo orquestrado sem nenhum código de servidor customizado.", technologies:["n8n","Docker","Gemini API"], github:"https://github.com/Wessel2007/telegram-gemini-bot", demo:null, status:"done" },
      ],
    },
    skills: {
      label: "// Stack Técnico",
      title: "Arquitetura de Domínio",
      description: "Stack organizado por responsabilidade do sistema. Cada camada reflete um papel distinto em como construo software inteligente ponta a ponta: de inferência local com IA até automação de scraping web.",
      layers: [
        { index:"01", title:"Camada de Interface",    technologies:["React","Next.js","React Native","Expo","TypeScript","JavaScript","HTML","CSS","Tailwind","shadcn/ui","Framer Motion"] },
        { index:"02", title:"Camada de Inteligência", technologies:["Python","YOLO","OpenCV","PyTorch","NumPy","Pandas","OCR","Ollama","Roboflow","CVAT"] },
        { index:"03", title:"Camada de Dados",        technologies:["PostgreSQL","MySQL","Supabase","Prisma","SQL","DBeaver"] },
        { index:"04", title:"Camada de Integração",   technologies:["FastAPI","Playwright","REST APIs","n8n","Arduino","IoT","Airflow"] },
        { index:"05", title:"Camada de Deploy",       technologies:["Git","GitHub","Docker","Vercel"] },
      ],
    },
    hackathons: {
      label: "// Hackathons & Reconhecimentos",
      title: "Sob Pressão, No Pódio",
      description: "Prazos curtos, banca de jurados real e software funcionando até o deadline — um tipo de prova técnica diferente de um projeto de portfólio.",
      items: [
        {
          place: "3º Lugar",
          award: "Premiado",
          title: "Hackathon Biopark — Rastreador de Protocolos",
          org: "Biopark",
          description: "Construí uma plataforma de rastreamento automatizado de protocolos (scraping com Playwright + assistente de IA via Ollama + dashboard admin) do zero durante o evento. Ficamos em 3º lugar geral e recebemos premiação.",
          highlight: true,
        },
        {
          place: "4º Lugar",
          award: "Finalista",
          title: "Hackatour 2026 — Raiz Iguaçu",
          org: "Hackatour",
          description: "Projetei e entreguei uma plataforma full-stack de turismo comunitário para produtores locais da região do Iguaçu, incluindo dashboard admin em tempo real e gestão de totens com QR Code. Ficamos em 4º lugar, sem premiação.",
          highlight: false,
        },
      ],
    },
    about: {
      label: "// Sobre",
      title: "Engenheiro em Formação, Construtor por Prática",
      bio: [
        "Sou estudante/desenvolvedor de IA e Visão Computacional focado em transformar ideias técnicas complexas em protótipos funcionais fáceis de inspecionar e melhorar.",
        "Meus projetos mais fortes estão entre o comportamento do modelo e as restrições do mundo real: pipelines de imagem, sistemas orientados a sensores e dashboards que tornam resultados legíveis.",
        "Me preocupo com implementação limpa, avaliação honesta e interfaces que tornam as decisões de engenharia visíveis sem transformar o produto em ruído visual.",
      ],
      signalLabel: "Sinal Atual",
      signal: "Em busca de estágios, vagas júnior, colaborações de pesquisa e projetos de IA, Visão Computacional e sistemas embarcados.",
      stats: [
        { value:"14",  label:"Projetos" },
        { value:"2",   label:"Hackathons" },
        { value:"25+", label:"Tecnologias" },
        { value:"5",   label:"Domínios Técnicos" },
      ],
    },
    publications: {
      label: "// Pesquisa",
      title: "Publicações Científicas",
      description: "Pesquisa revisada por pares na interseção de aprendizado de máquina e suporte à decisão clínica.",
      countLabel: "Artigo Publicado",
      readBtn: "Ler Artigo",
      items: [
        {
          title: "Machine Learning na Predição de Doenças Cardíacas: Uma Análise Comparativa de Algoritmos de Classificação",
          journal: "Revista Eletrônica Multidisciplinar de Investigação Científica (REMICI)",
          volume: "Vol. 5, Nº 23 · 2026",
          doi: "https://doi.org/10.47402/remici.v5n23696926",
          url: "https://remici.com.br/index.php/revista/article/view/970",
          keywords: ["Machine Learning", "Doença Cardíaca", "Random Forest", "Classificação", "Suporte à Decisão Clínica"],
          abstract: "Desenvolve e avalia cinco modelos de ML supervisionado usando o dataset Cleveland Heart Disease (303 registros, 13 atributos clínicos). Acurácia de validação cruzada entre 77,18%–83,45%; Random Forest obteve o maior AUC (90,10%) e recall para casos positivos (96,97%), demonstrando potencial como ferramenta de suporte à decisão clínica.",
          license: "CC BY-NC-SA 4.0",
        },
      ],
    },
    contact: {
      label: "// Contato",
      title: "Pronto para conectar o sinal.",
      description: "Se você está contratando para IA, Visão Computacional, prototipagem full-stack ou software próximo ao hardware, este é o caminho mais rápido.",
      links: [
        { label:"GitHub",   href:"https://github.com/Wessel2007",           tag:"CÓDIGO" },
        { label:"LinkedIn", href:"https://www.linkedin.com/in/luizwessel/", tag:"REDE"   },
        { label:"Email",    href:"mailto:heyxist3r@gmail.com",              tag:"DIRETO" },
      ],
      footerBuild:  "BUILD: REACT 18 / VITE / CANVAS API",
      footerStatus: "STATUS DO SISTEMA: ABERTO A OPORTUNIDADES",
      footerSync:   "ÚLTIMA SYNC: 2026 / PORT_OS v3.0",
    },
  },
};

// ─── Tech Badge Color Map ─────────────────────────────────────────────────────
export const TECH_COLORS = {
  Python:          { bg:"rgba(255,212,0,0.07)",    border:"rgba(255,212,0,0.32)",    text:"#FFD44D" },
  YOLO:            { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.32)",    text:"#F87171" },
  YOLOv11:         { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.32)",    text:"#F87171" },
  EasyOCR:         { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  FastAPI:         { bg:"rgba(5,150,105,0.07)",    border:"rgba(5,150,105,0.32)",    text:"#34D399" },
  React:           { bg:"rgba(56,189,248,0.07)",   border:"rgba(56,189,248,0.32)",   text:"#38BDF8" },
  Supabase:        { bg:"rgba(52,211,153,0.07)",   border:"rgba(52,211,153,0.32)",   text:"#34D399" },
  Arduino:         { bg:"rgba(0,151,167,0.07)",    border:"rgba(0,151,167,0.32)",    text:"#00BCD4" },
  OpenCV:          { bg:"rgba(71,85,105,0.10)",    border:"rgba(100,116,139,0.35)",  text:"#94A3B8" },
  PyTorch:         { bg:"rgba(238,76,44,0.07)",    border:"rgba(238,76,44,0.32)",    text:"#F97316" },
  NumPy:           { bg:"rgba(77,128,196,0.07)",   border:"rgba(77,128,196,0.32)",   text:"#60A5FA" },
  CCXT:            { bg:"rgba(234,179,8,0.07)",    border:"rgba(234,179,8,0.32)",    text:"#FACC15" },
  Pandas:          { bg:"rgba(99,102,241,0.07)",   border:"rgba(99,102,241,0.32)",   text:"#818CF8" },
  "Claude API":    { bg:"rgba(201,136,78,0.07)",   border:"rgba(201,136,78,0.32)",   text:"#D4956A" },
  "Next.js":       { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.22)",  text:"#F1F5F9" },
  TypeScript:      { bg:"rgba(49,120,198,0.07)",   border:"rgba(49,120,198,0.32)",   text:"#60A5FA" },
  JavaScript:      { bg:"rgba(234,179,8,0.07)",    border:"rgba(234,179,8,0.32)",    text:"#FACC15" },
  Vite:            { bg:"rgba(149,87,234,0.07)",   border:"rgba(149,87,234,0.32)",   text:"#A78BFA" },
  Tailwind:        { bg:"rgba(6,182,212,0.07)",    border:"rgba(6,182,212,0.32)",    text:"#22D3EE" },
  "Tailwind CSS":  { bg:"rgba(6,182,212,0.07)",    border:"rgba(6,182,212,0.32)",    text:"#22D3EE" },
  PostgreSQL:      { bg:"rgba(51,103,145,0.07)",   border:"rgba(51,103,145,0.32)",   text:"#60A5FA" },
  "shadcn/ui":     { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.20)",  text:"#CBD5E1" },
  Recharts:        { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.28)",    text:"#FCA5A5" },
  "Framer Motion": { bg:"rgba(236,72,153,0.07)",   border:"rgba(236,72,153,0.28)",   text:"#F472B6" },
  "AI/ML":         { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  "IA/ML":         { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  HTML:            { bg:"rgba(234,88,12,0.07)",    border:"rgba(234,88,12,0.32)",    text:"#FB923C" },
  CSS:             { bg:"rgba(59,130,246,0.07)",   border:"rgba(59,130,246,0.32)",   text:"#93C5FD" },
  OCR:             { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  Roboflow:        { bg:"rgba(99,102,241,0.07)",   border:"rgba(99,102,241,0.32)",   text:"#818CF8" },
  CVAT:            { bg:"rgba(71,85,105,0.10)",    border:"rgba(100,116,139,0.35)",  text:"#94A3B8" },
  MySQL:           { bg:"rgba(234,88,12,0.07)",    border:"rgba(234,88,12,0.32)",    text:"#FB923C" },
  SQL:             { bg:"rgba(51,103,145,0.07)",   border:"rgba(51,103,145,0.32)",   text:"#7DD3FC" },
  DBeaver:         { bg:"rgba(71,85,105,0.10)",    border:"rgba(100,116,139,0.35)",  text:"#94A3B8" },
  "REST APIs":     { bg:"rgba(5,150,105,0.07)",    border:"rgba(5,150,105,0.32)",    text:"#6EE7B7" },
  IoT:             { bg:"rgba(0,151,167,0.07)",    border:"rgba(0,151,167,0.32)",    text:"#67E8F9" },
  Airflow:         { bg:"rgba(14,165,233,0.07)",   border:"rgba(14,165,233,0.32)",   text:"#38BDF8" },
  Git:             { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.32)",    text:"#FCA5A5" },
  GitHub:          { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.20)",  text:"#CBD5E1" },
  Docker:          { bg:"rgba(14,165,233,0.07)",   border:"rgba(14,165,233,0.32)",   text:"#0EA5E9" },
  Vercel:          { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.22)",  text:"#F1F5F9" },
  Playwright:      { bg:"rgba(46,139,87,0.07)",    border:"rgba(46,139,87,0.32)",    text:"#4ADE80" },
  Ollama:          { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.18)",  text:"#CBD5E1" },
  DuckDB:            { bg:"rgba(255,196,0,0.07)",   border:"rgba(255,196,0,0.32)",   text:"#FCD34D" },
  "Delta Lake":      { bg:"rgba(0,111,238,0.07)",   border:"rgba(0,111,238,0.32)",   text:"#60A5FA" },
  "Apache Parquet":  { bg:"rgba(80,190,130,0.07)",  border:"rgba(80,190,130,0.32)",  text:"#6EE7B7" },
  Streamlit:         { bg:"rgba(255,75,75,0.07)",   border:"rgba(255,75,75,0.32)",   text:"#FCA5A5" },
  Groq:              { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.20)", text:"#E2E8F0" },
  "Llama 3.1":       { bg:"rgba(99,102,241,0.07)",  border:"rgba(99,102,241,0.32)",  text:"#818CF8" },
  ColorThief:        { bg:"rgba(236,72,153,0.07)",  border:"rgba(236,72,153,0.28)",  text:"#F472B6" },
  Pillow:            { bg:"rgba(14,165,233,0.07)",  border:"rgba(14,165,233,0.32)",  text:"#38BDF8" },
  "Machine Learning": { bg:"rgba(168,85,247,0.07)", border:"rgba(168,85,247,0.32)", text:"#C084FC" },
  "Data Science":  { bg:"rgba(99,102,241,0.07)",   border:"rgba(99,102,241,0.32)",   text:"#818CF8" },
  "Canvas API":    { bg:"rgba(234,88,12,0.07)",    border:"rgba(234,88,12,0.28)",    text:"#FB923C" },
  Babel:           { bg:"rgba(250,204,21,0.07)",   border:"rgba(250,204,21,0.28)",   text:"#FDE047" },
  "React Native":  { bg:"rgba(56,189,248,0.07)",   border:"rgba(56,189,248,0.32)",   text:"#38BDF8" },
  Expo:            { bg:"rgba(56,189,248,0.05)",   border:"rgba(56,189,248,0.24)",   text:"#7DD3FC" },
  i18next:         { bg:"rgba(38,166,154,0.07)",   border:"rgba(38,166,154,0.32)",   text:"#2DD4BF" },
  Reanimated:      { bg:"rgba(236,72,153,0.07)",   border:"rgba(236,72,153,0.28)",   text:"#F472B6" },
  Prisma:          { bg:"rgba(56,189,248,0.07)",   border:"rgba(56,189,248,0.30)",   text:"#67E8F9" },
  Zod:             { bg:"rgba(59,130,246,0.07)",   border:"rgba(59,130,246,0.32)",   text:"#93C5FD" },
  Vitest:          { bg:"rgba(250,204,21,0.07)",   border:"rgba(250,204,21,0.30)",   text:"#FDE047" },
  n8n:             { bg:"rgba(234,76,137,0.07)",   border:"rgba(234,76,137,0.32)",   text:"#F472B6" },
  "Gemini API":    { bg:"rgba(99,102,241,0.07)",   border:"rgba(99,102,241,0.32)",   text:"#A5B4FC" },
};

export const BADGE_DEFAULT = { bg:"rgba(20,30,50,0.60)", border:"rgba(51,65,85,0.45)", text:"#94A3B8" };
