// ─── Portfolio Content Data ───────────────────────────────────────────────────

window.CONTENT = {
  en: {
    navLinks: [
      { label: "Featured", href: "#featured" },
      { label: "Projects", href: "#projects" },
      { label: "Skills",   href: "#skills"   },
      { label: "About",    href: "#about"    },
      { label: "Contact",  href: "#contact"  },
    ],
    bootLines: [
      "> Booting recruiter-ready portfolio interface...",
      "[ OK ] Computer vision modules indexed",
      "[ OK ] Edge systems telemetry linked",
      "[ OK ] Professional signal calibrated",
    ],
    hero: {
      role: "AI & Computer Vision Developer",
      name: "Luiz Wessel",
      tagline: "Engineering AI systems from the edge of the void.",
      description: "I build practical AI, computer vision, and edge systems with clear interfaces, measurable behavior, and documentation that helps teams understand the system.",
      ctaPrimary: "Review Featured Work",
      ctaSecondary: "Get in Touch",
      hudSignal: "SIGNAL: HUMAN-READABLE AI",
      hudStatus: "STATUS: AVAILABLE",
    },
    featured: {
      label: "// Featured Project",
      title: "A project framed as an engineering case study",
      intro: "A portfolio highlight focused on the work recruiters care about: what problem was solved, how the system was designed, and which technical decisions made it useful.",
      problemLabel: "Problem",
      solutionLabel: "Solution",
      signalLabel: "Technical Signal",
      techLabel: "Technologies",
      githubBtn: "GitHub Repository",
      demoBtn: "Live Demo",
      project: {
        title: "Gate Vision — Vehicular Access Control",
        category: "Featured Case Study",
        problem: "Condominiums need reliable, automated vehicle access without a manual operator — and the solution must work in real-world lighting with Mercosul plates.",
        solution: "Python/FastAPI backend runs YOLO detection + EasyOCR with CLAHE preprocessing; React admin dashboard via Supabase handles residents, logs, and camera config; Arduino receives serial commands to physically open the gate.",
        technologies: ["Python","YOLO","EasyOCR","FastAPI","React","Supabase","Arduino","OpenCV"],
        github: "https://github.com/Wessel2007/Gate-Vision",
        demo: null,
        signal: "End-to-end system thinking: CV pipeline + REST API + hardware actuation + admin interface",
      },
    },
    projects: {
      label: "// Project Archive",
      title: "Selected Work",
      problemLabel: "Problem",
      solutionLabel: "Solution",
      githubLabel: "GitHub",
      demoLabel: "Demo",
      items: [
        { title:"Vehicle Plate Detection", category:"Computer Vision", problem:"Detecting Mercosul plates in real-world images requires a robust, reusable module before any OCR or access-control logic.", solution:"Trained YOLOv11 to locate plate regions, applied CLAHE contrast enhancement and a fast crop pipeline feeding clean images to downstream OCR.", technologies:["Python","YOLOv11","OpenCV","PyTorch","NumPy"], github:"https://github.com/Wessel2007/deteccao-placas-veiculares", demo:null },
        { title:"Corn Instance Segmentation", category:"Computer Vision", problem:"Measuring and segmenting individual corn plants requires precise instance-level detection for agricultural analysis.", solution:"Built a CV pipeline using CVAT for annotation, OpenCV for processing, and Python for instance segmentation of real field images.", technologies:["Python","OpenCV","CVAT"], github:"https://github.com/Wessel2007/corn-instance-segmentation", demo:null },
        { title:"Crypto Insight AI", category:"Applied AI / Finance", problem:"Tracking technical indicators across timeframes for multiple cryptos is hard to interpret without a unified scoring layer.", solution:"FastAPI backend pulls live data via CCXT, computes RSI/EMA/MACD, runs a weighted scoring engine, calls Claude for plain-language summaries.", technologies:["Python","FastAPI","CCXT","Pandas","Claude API","Next.js","TypeScript"], github:"https://github.com/Wessel2007/crypto-insight-ai", demo:null },
        { title:"Raiz Iguaçu — Hackatour 2026", category:"Full-Stack Web", problem:"Community tourism in the Iguaçu region lacks a scalable platform for local producers and travelers.", solution:"Full-stack platform with experience discovery, producer onboarding, admin dashboard with real-time metrics, QR-code totem management, and AI-generated visitor insights.", technologies:["React","TypeScript","Vite","Tailwind","FastAPI","PostgreSQL","shadcn/ui"], github:"https://github.com/Wessel2007/Hackatour-Cataratas", demo:null },
        { title:"Pharm Assist", category:"Applied AI", problem:"Public pharmacy management needed an AI-assisted tool to track and optimize medication dispensing processes.", solution:"Collaborative academic project with Biopark AI course for the Prefeitura de Toledo/PR, applying AI to pharmacy workflows.", technologies:["Python","AI/ML"], github:"https://github.com/Wessel2007/Pharm-Assist", demo:null },
        { title:"New AI Invest", category:"Web / Finance", problem:"Investors managing multiple asset classes need a clear view of portfolio drift without relying on spreadsheets.", solution:"React SPA with full asset CRUD, configurable target allocations, rebalancing calculator, Recharts dashboards, and diversification insights.", technologies:["React","JavaScript","Tailwind CSS","Recharts"], github:"https://github.com/Wessel2007/new-ai-invest", demo:null },
        { title:"Neural HUD Portfolio", category:"Web Interface", problem:"Technical portfolios often fail to communicate engineering judgment or how problems were actually solved.", solution:"Recruiter-ready Next.js interface framing every project as a structured engineering case study with bilingual support and HUD design system.", technologies:["Next.js","TypeScript","Tailwind CSS","Framer Motion"], github:"https://github.com/Wessel2007/Neural-HUD-Portfolio-AI-Developer-Interface", demo:null },
        { title:"Tornado Brasil — Storm Prediction", category:"AI / Meteorology", problem:"Southern Brazil has documented tornado activity but lacks accessible, automated risk-mapping tools to alert communities before extreme weather events.", solution:"Planned ML system to process meteorological data (INMET/ERA5), identify historical storm patterns, and generate regional risk maps for the South of Brazil. Currently in early development.", technologies:["Python","Machine Learning","Pandas","NumPy","Data Science"], github:"https://github.com/Wessel2007/tornado_project", demo:null },
        { title:"Biopark Hackathon — Protocol Tracker", category:"Full-Stack / Applied AI", problem:"Tracking construction and business protocols across multiple public agencies (cartórios, COPEL, SANEPAR, CBPR) requires constant manual monitoring with no centralized view.", solution:"Web platform with automated Playwright scraping of real public portals, AI chat assistant via Ollama/Llama, PDF reports, screenshot evidence logging, and a full admin dashboard. Built during hackathon.", technologies:["Python","FastAPI","React","Vite","Tailwind","Supabase","Playwright","Ollama"], github:"https://github.com/Wessel2007/hackathon-biopark", demo:null },
      ],
    },
    skills: {
      label: "// Tech Stack",
      title: "Domain Architecture",
      description: "Stack organized by system responsibility — not arbitrary language lists. Each layer reflects a distinct role in how I build intelligent, end-to-end software: from local AI inference to automated web scraping.",
      layers: [
        { index:"01", title:"Interface Layer",    technologies:["React","Next.js","TypeScript","JavaScript","HTML","CSS","Tailwind","shadcn/ui","Framer Motion"] },
        { index:"02", title:"Intelligence Layer", technologies:["Python","YOLO","OpenCV","PyTorch","NumPy","Pandas","OCR","Ollama","Roboflow","CVAT"] },
        { index:"03", title:"Data Layer",         technologies:["PostgreSQL","MySQL","Supabase","SQL","DBeaver"] },
        { index:"04", title:"Integration Layer",  technologies:["FastAPI","Playwright","REST APIs","Arduino","IoT","Airflow"] },
        { index:"05", title:"Deployment Layer",   technologies:["Git","GitHub","Docker","Vercel"] },
      ],
    },
    about: {
      label: "// About",
      title: "Engineer in Training, Builder by Practice",
      bio: [
        "I'm an AI and Computer Vision student/developer focused on turning difficult technical ideas into working prototypes that are easy to inspect, explain, and improve.",
        "My strongest projects sit between model behavior and real-world constraints: image pipelines, sensor-driven systems, edge prototypes, and the dashboards that make results readable.",
        "I care about clean implementation, honest evaluation, and interfaces that make engineering decisions visible without turning the product into visual noise.",
      ],
      signalLabel: "Current Signal",
      signal: "Looking for internships, junior roles, research collaborations, and project work around AI, Computer Vision, and edge systems.",
      stats: [
        { value:"9",   label:"Projects Built" },
        { value:"2",   label:"Hackathons" },
        { value:"20+", label:"Technologies" },
        { value:"5",   label:"Tech Domains" },
      ],
    },
    contact: {
      label: "// Contact",
      title: "Ready to connect the signal.",
      description: "If you are hiring for AI, Computer Vision, full-stack prototyping, or hardware-adjacent software, this is the fastest route to reach me.",
      links: [
        { label:"GitHub",   href:"https://github.com/Wessel2007",              tag:"CODE"    },
        { label:"LinkedIn", href:"https://www.linkedin.com/in/luizwessel/",    tag:"NETWORK" },
        { label:"Email",    href:"mailto:heyxist3r@gmail.com",                 tag:"DIRECT"  },
      ],
      footerBuild:  "BUILD: REACT 18 / BABEL / CANVAS API",
      footerStatus: "SYSTEM STATUS: OPEN TO OPPORTUNITIES",
      footerSync:   "LAST SYNC: 2026 / PORT_OS v3.0",
    },
  },

  pt: {
    navLinks: [
      { label: "Destaque",  href: "#featured" },
      { label: "Projetos",  href: "#projects"  },
      { label: "Skills",    href: "#skills"    },
      { label: "Sobre",     href: "#about"     },
      { label: "Contato",   href: "#contact"   },
    ],
    bootLines: [
      "> Iniciando interface de portfólio...",
      "[ OK ] Módulos de visão computacional indexados",
      "[ OK ] Telemetria de sistemas embarcados vinculada",
      "[ OK ] Sinal profissional calibrado",
    ],
    hero: {
      role: "Desenvolvedor de IA & Visão Computacional",
      name: "Luiz Wessel",
      tagline: "Construindo sistemas de IA na fronteira do desconhecido.",
      description: "Desenvolvo sistemas práticos de IA, visão computacional e edge computing com interfaces claras, comportamento mensurável e documentação que ajuda equipes a entender o sistema.",
      ctaPrimary: "Ver Projeto em Destaque",
      ctaSecondary: "Entrar em Contato",
      hudSignal: "SINAL: IA LEGÍVEL POR HUMANOS",
      hudStatus: "STATUS: DISPONÍVEL",
    },
    featured: {
      label: "// Projeto em Destaque",
      title: "Um projeto como estudo de caso de engenharia",
      intro: "Destaque focado no que recrutadores realmente querem ver: qual problema foi resolvido, como o sistema foi projetado e quais decisões técnicas o tornaram útil.",
      problemLabel: "Problema",
      solutionLabel: "Solução",
      signalLabel: "Sinal Técnico",
      techLabel: "Tecnologias",
      githubBtn: "Repositório GitHub",
      demoBtn: "Demo ao Vivo",
      project: {
        title: "Gate Vision — Controle de Acesso Veicular",
        category: "Estudo de Caso em Destaque",
        problem: "Condomínios precisam de controle de acesso veicular automatizado — e a solução precisa funcionar em condições reais de iluminação com placas Mercosul.",
        solution: "Backend Python/FastAPI com pipeline YOLO + EasyOCR e pré-processamento CLAHE; dashboard React via Supabase para moradores, logs e câmeras; Arduino recebe comandos seriais para abertura física da cancela.",
        technologies: ["Python","YOLO","EasyOCR","FastAPI","React","Supabase","Arduino","OpenCV"],
        github: "https://github.com/Wessel2007/Gate-Vision",
        demo: null,
        signal: "Pensamento ponta a ponta: pipeline CV + API REST + atuação em hardware + interface administrativa",
      },
    },
    projects: {
      label: "// Arquivo de Projetos",
      title: "Trabalhos Selecionados",
      problemLabel: "Problema",
      solutionLabel: "Solução",
      githubLabel: "GitHub",
      demoLabel: "Demo",
      items: [
        { title:"Detecção de Placas Veiculares", category:"Visão Computacional", problem:"Detectar placas Mercosul em imagens reais exige módulo robusto antes de qualquer lógica de OCR.", solution:"Treinei YOLOv11 para localizar placas, apliquei CLAHE e implementei pipeline de recorte para OCR.", technologies:["Python","YOLOv11","OpenCV","PyTorch","NumPy"], github:"https://github.com/Wessel2007/deteccao-placas-veiculares", demo:null },
        { title:"Segmentação de Milho", category:"Visão Computacional", problem:"Medir e segmentar plantas de milho exige detecção precisa no nível de instância.", solution:"Pipeline de CV com CVAT para anotação, OpenCV para processamento e Python para segmentação.", technologies:["Python","OpenCV","CVAT"], github:"https://github.com/Wessel2007/corn-instance-segmentation", demo:null },
        { title:"Crypto Insight AI", category:"IA Aplicada / Finanças", problem:"Acompanhar indicadores técnicos em múltiplos timeframes é difícil sem uma camada unificada de scoring.", solution:"Backend FastAPI com CCXT, computa RSI/EMA/MACD, engine de scoring ponderado e Claude para resumos em linguagem natural.", technologies:["Python","FastAPI","CCXT","Pandas","Claude API","Next.js","TypeScript"], github:"https://github.com/Wessel2007/crypto-insight-ai", demo:null },
        { title:"Raiz Iguaçu — Hackatour 2026", category:"Full-Stack Web", problem:"Turismo comunitário no Iguaçu sem plataforma escalável para produtores e turistas.", solution:"Plataforma full-stack com descoberta de experiências, dashboard admin, totens QR Code e insights de IA.", technologies:["React","TypeScript","Vite","Tailwind","FastAPI","PostgreSQL","shadcn/ui"], github:"https://github.com/Wessel2007/Hackatour-Cataratas", demo:null },
        { title:"Pharm Assist", category:"IA Aplicada", problem:"Gestão farmacêutica municipal precisava de ferramenta com IA para monitorar dispensação.", solution:"Projeto acadêmico com Biopark AI para Prefeitura de Toledo/PR, aplicando IA em workflows farmacêuticos.", technologies:["Python","IA/ML"], github:"https://github.com/Wessel2007/Pharm-Assist", demo:null },
        { title:"New AI Invest", category:"Web / Finanças", problem:"Investidores precisam de visão clara do desvio do portfólio sem depender de planilhas.", solution:"SPA React com CRUD de ativos, alocações-alvo, calculadora de rebalanceamento e dashboards Recharts.", technologies:["React","JavaScript","Tailwind CSS","Recharts"], github:"https://github.com/Wessel2007/new-ai-invest", demo:null },
        { title:"Neural HUD Portfolio", category:"Interface Web", problem:"Portfólios técnicos falham em comunicar julgamento de engenharia e contexto dos projetos.", solution:"Interface Next.js com cada projeto como estudo de caso estruturado, suporte bilíngue e design system HUD.", technologies:["Next.js","TypeScript","Tailwind CSS","Framer Motion"], github:"https://github.com/Wessel2007/Neural-HUD-Portfolio-AI-Developer-Interface", demo:null },
        { title:"Tornado Brasil — Previsão de Tempestades", category:"IA / Meteorologia", problem:"O sul do Brasil tem registro de tornados mas carece de ferramentas automatizadas de mapeamento de risco para alertar comunidades antes de eventos extremos.", solution:"Sistema de ML planejado para processar dados meteorológicos (INMET/ERA5), identificar padrões históricos de tempestades e gerar mapas de risco regional para o sul do Brasil. Em desenvolvimento inicial.", technologies:["Python","Machine Learning","Pandas","NumPy","Data Science"], github:"https://github.com/Wessel2007/tornado_project", demo:null },
        { title:"Hackathon Biopark — Rastreador de Protocolos", category:"Full-Stack / IA Aplicada", problem:"Acompanhar protocolos de obras e negócios em múltiplos órgãos públicos (cartórios, COPEL, SANEPAR, CBPR) exige monitoramento manual constante sem visão centralizada.", solution:"Plataforma web com scraping automatizado via Playwright em portais públicos reais, assistente de IA com Ollama/Llama, relatórios PDF, evidências por screenshot e dashboard administrativo. Desenvolvido em hackathon.", technologies:["Python","FastAPI","React","Vite","Tailwind","Supabase","Playwright","Ollama"], github:"https://github.com/Wessel2007/hackathon-biopark", demo:null },
      ],
    },
    skills: {
      label: "// Stack Técnico",
      title: "Arquitetura de Domínio",
      description: "Stack organizado por responsabilidade do sistema. Cada camada reflete um papel distinto em como construo software inteligente ponta a ponta: de inferência local com IA até automação de scraping web.",
      layers: [
        { index:"01", title:"Camada de Interface",    technologies:["React","Next.js","TypeScript","JavaScript","HTML","CSS","Tailwind","shadcn/ui","Framer Motion"] },
        { index:"02", title:"Camada de Inteligência", technologies:["Python","YOLO","OpenCV","PyTorch","NumPy","Pandas","OCR","Ollama","Roboflow","CVAT"] },
        { index:"03", title:"Camada de Dados",        technologies:["PostgreSQL","MySQL","Supabase","SQL","DBeaver"] },
        { index:"04", title:"Camada de Integração",   technologies:["FastAPI","Playwright","REST APIs","Arduino","IoT","Airflow"] },
        { index:"05", title:"Camada de Deploy",       technologies:["Git","GitHub","Docker","Vercel"] },
      ],
    },
    about: {
      label: "// Sobre",
      title: "Engenheiro em Formação, Construtor por Prática",
      bio: [
        "Sou estudante/desenvolvedor de IA e Visão Computacional focado em transformar ideias técnicas complexas em protótipos funcionais fáceis de inspecionar e melhorar.",
        "Meus projetos mais fortes estão entre o comportamento do modelo e as restrições do mundo real: pipelines de imagem, sistemas orientados a sensores e dashboards que tornam resultados legíveis.",
        "Me preocupo com implementação limpa, avaliação honesta e interfaces que tornam as decisões de engenharia visíveis sem transformar o produto em ruído visual.",
      ],
      signalLabel: "Sinal Atual",
      signal: "Em busca de estágios, vagas júnior, colaborações de pesquisa e projetos de IA, Visão Computacional e sistemas embarcados.",
      stats: [
        { value:"9",   label:"Projetos" },
        { value:"2",   label:"Hackathons" },
        { value:"20+", label:"Tecnologias" },
        { value:"5",   label:"Domínios Técnicos" },
      ],
    },
    contact: {
      label: "// Contato",
      title: "Pronto para conectar o sinal.",
      description: "Se você está contratando para IA, Visão Computacional, prototipagem full-stack ou software próximo ao hardware, este é o caminho mais rápido.",
      links: [
        { label:"GitHub",   href:"https://github.com/Wessel2007",           tag:"CÓDIGO" },
        { label:"LinkedIn", href:"https://www.linkedin.com/in/luizwessel/", tag:"REDE"   },
        { label:"Email",    href:"mailto:heyxist3r@gmail.com",              tag:"DIRETO" },
      ],
      footerBuild:  "BUILD: REACT 18 / BABEL / CANVAS API",
      footerStatus: "STATUS DO SISTEMA: ABERTO A OPORTUNIDADES",
      footerSync:   "ÚLTIMA SYNC: 2026 / PORT_OS v3.0",
    },
  },
};

// ─── Tech Badge Color Map ─────────────────────────────────────────────────────
window.TECH_COLORS = {
  Python:          { bg:"rgba(255,212,0,0.07)",    border:"rgba(255,212,0,0.32)",    text:"#FFD44D" },
  YOLO:            { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.32)",    text:"#F87171" },
  YOLOv11:         { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.32)",    text:"#F87171" },
  EasyOCR:         { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  FastAPI:         { bg:"rgba(5,150,105,0.07)",    border:"rgba(5,150,105,0.32)",    text:"#34D399" },
  React:           { bg:"rgba(56,189,248,0.07)",   border:"rgba(56,189,248,0.32)",   text:"#38BDF8" },
  Supabase:        { bg:"rgba(52,211,153,0.07)",   border:"rgba(52,211,153,0.32)",   text:"#34D399" },
  Arduino:         { bg:"rgba(0,151,167,0.07)",    border:"rgba(0,151,167,0.32)",    text:"#00BCD4" },
  OpenCV:          { bg:"rgba(71,85,105,0.10)",    border:"rgba(100,116,139,0.35)",  text:"#94A3B8" },
  PyTorch:         { bg:"rgba(238,76,44,0.07)",    border:"rgba(238,76,44,0.32)",    text:"#F97316" },
  NumPy:           { bg:"rgba(77,128,196,0.07)",   border:"rgba(77,128,196,0.32)",   text:"#60A5FA" },
  CCXT:            { bg:"rgba(234,179,8,0.07)",    border:"rgba(234,179,8,0.32)",    text:"#FACC15" },
  Pandas:          { bg:"rgba(99,102,241,0.07)",   border:"rgba(99,102,241,0.32)",   text:"#818CF8" },
  "Claude API":    { bg:"rgba(201,136,78,0.07)",   border:"rgba(201,136,78,0.32)",   text:"#D4956A" },
  "Next.js":       { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.22)",  text:"#F1F5F9" },
  TypeScript:      { bg:"rgba(49,120,198,0.07)",   border:"rgba(49,120,198,0.32)",   text:"#60A5FA" },
  JavaScript:      { bg:"rgba(234,179,8,0.07)",    border:"rgba(234,179,8,0.32)",    text:"#FACC15" },
  Vite:            { bg:"rgba(149,87,234,0.07)",   border:"rgba(149,87,234,0.32)",   text:"#A78BFA" },
  Tailwind:        { bg:"rgba(6,182,212,0.07)",    border:"rgba(6,182,212,0.32)",    text:"#22D3EE" },
  "Tailwind CSS":  { bg:"rgba(6,182,212,0.07)",    border:"rgba(6,182,212,0.32)",    text:"#22D3EE" },
  PostgreSQL:      { bg:"rgba(51,103,145,0.07)",   border:"rgba(51,103,145,0.32)",   text:"#60A5FA" },
  "shadcn/ui":     { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.20)",  text:"#CBD5E1" },
  Recharts:        { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.28)",    text:"#FCA5A5" },
  "Framer Motion": { bg:"rgba(236,72,153,0.07)",   border:"rgba(236,72,153,0.28)",   text:"#F472B6" },
  "AI/ML":         { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  "IA/ML":         { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  HTML:            { bg:"rgba(234,88,12,0.07)",    border:"rgba(234,88,12,0.32)",    text:"#FB923C" },
  CSS:             { bg:"rgba(59,130,246,0.07)",   border:"rgba(59,130,246,0.32)",   text:"#93C5FD" },
  OCR:             { bg:"rgba(168,85,247,0.07)",   border:"rgba(168,85,247,0.32)",   text:"#C084FC" },
  Roboflow:        { bg:"rgba(99,102,241,0.07)",   border:"rgba(99,102,241,0.32)",   text:"#818CF8" },
  CVAT:            { bg:"rgba(71,85,105,0.10)",    border:"rgba(100,116,139,0.35)",  text:"#94A3B8" },
  MySQL:           { bg:"rgba(234,88,12,0.07)",    border:"rgba(234,88,12,0.32)",    text:"#FB923C" },
  SQL:             { bg:"rgba(51,103,145,0.07)",   border:"rgba(51,103,145,0.32)",   text:"#7DD3FC" },
  DBeaver:         { bg:"rgba(71,85,105,0.10)",    border:"rgba(100,116,139,0.35)",  text:"#94A3B8" },
  "REST APIs":     { bg:"rgba(5,150,105,0.07)",    border:"rgba(5,150,105,0.32)",    text:"#6EE7B7" },
  IoT:             { bg:"rgba(0,151,167,0.07)",    border:"rgba(0,151,167,0.32)",    text:"#67E8F9" },
  Airflow:         { bg:"rgba(14,165,233,0.07)",   border:"rgba(14,165,233,0.32)",   text:"#38BDF8" },
  Git:             { bg:"rgba(239,68,68,0.07)",    border:"rgba(239,68,68,0.32)",    text:"#FCA5A5" },
  GitHub:          { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.20)",  text:"#CBD5E1" },
  Docker:          { bg:"rgba(14,165,233,0.07)",   border:"rgba(14,165,233,0.32)",   text:"#0EA5E9" },
  Vercel:          { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.22)",  text:"#F1F5F9" },
  Playwright:      { bg:"rgba(46,139,87,0.07)",    border:"rgba(46,139,87,0.32)",    text:"#4ADE80" },
  Ollama:          { bg:"rgba(248,250,252,0.05)",  border:"rgba(248,250,252,0.18)",  text:"#CBD5E1" },
  "Machine Learning": { bg:"rgba(168,85,247,0.07)", border:"rgba(168,85,247,0.32)", text:"#C084FC" },
  "Data Science":  { bg:"rgba(99,102,241,0.07)",   border:"rgba(99,102,241,0.32)",   text:"#818CF8" },
};
window.BADGE_DEFAULT = { bg:"rgba(20,30,50,0.60)", border:"rgba(51,65,85,0.45)", text:"#94A3B8" };
